### ISSUE TITLE
broken at node 0.12

### ISSUE THREAD

**Issue by stdavis** [steveoh/grunt-esri-slurp#35]
I was able to slurp a few times successfully after upgrading to 0.12. However, then I started having the same problem as @steveoh. Progress bar gets to 100% then hangs. Worked fine after rolling back to 0.10.31.

**Comment by tomwayson** [comment]
:(

Windows?

**Comment by stdavis** [comment]
OSX for me. Windows for @steveoh.

**Comment by stdavis** [comment]
Beat my head on this for a while this afternoon and wasn't able to come up with a fix yet. Here's what I found out.

Looks like it broke at node 0.11+

The cause of the hanging is that there are several requests that never fire their callbacks. I set up some code to track this and have observed between 2 and 5 requests that never finish. It just hangs indefinitely.

Confirmed that we are using the latest versions of `async` and `request`. Tried older versions of `requests` but no luck. Also tried using `http` (core) instead of `requests` and had the same result.

Everything works fine if you drop the async limit from 50 to 1 but then it's maddenly slow.

**Comment by steveoh** [comment]
did you notice the http status code coming back from the requests @stdavis?

**Comment by stdavis** [comment]
No, but that was part of the problem. The callback that I could check the
status code in does not fire for the last few requests.

On Sun, Mar 22, 2015 at 10:12 PM, steveoh <notifications@github.com> wrote:

> did you notice the http status code coming back from the requests @stdavis
> <https://github.com/stdavis>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/steveoh/grunt-esri-slurp/issues/35#issuecomment-84789873>
> .
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by roemhildtg** [comment]
I'm at node version 0.12, and after running, it gets to about 17 or 18% and fails with `Fatal error: Cannot read property 'length' of undefined'` Am I doing something wrong or is this a related issue?

**Comment by stdavis** [comment]
@roemhildtg What esri api version are you slurping?

**Comment by roemhildtg** [comment]
@stdavis 3.13. I've also tried doing the 3.12 version but a similar result occurred. I tried it again later today, and it made it up to 85% before hanging. 

Question: Is 'slurping' actually downloading different files than if I were to download the api zip file from esri's support site?

**Comment by stdavis** [comment]
Yes. It's downloading a special AMD build. Then making some modifications to them to make it work with the dojo build system. If you are not wanting to plug the slurped files into the build system you shouldn't worry about this tool. Just download the data from esri and be done with it.

**Comment by roemhildtg** [comment]
That is my goal, I'm learning how to use the build tool and it wasn't working with the data from esri, and that was when I stumbled upon this.

**Comment by stdavis** [comment]
Then you have come to the right place. :) Only problem is this tool isn't working at node v0.11+ currently. You can downgrade or wait for a fix. I spent some time on this bug a few weeks ago and couldn't squash it. I'm taking a look at it again this afternoon to see if I can knock something loose. I believe that your troubles are related to this issue.

**Comment by roemhildtg** [comment]
Awesome, well I downgraded node on my linux dev machine and was able to get it working! Thanks for the help! I have a somewhat unrelated question about building with proj4, would you mind if i sent you a pm?

**Comment by stdavis** [comment]
@steveoh We should pair up on this next week. Seeing lots of 404's even when I load some URL's via my browser (e.g. http://js.arcgis.com/3.11amd/esri/nls/jsapi_ROOT.js).

**Comment by steveoh** [comment]
sounds good. I would like to get this working on node and io.

**Comment by steveoh** [comment]
closed with b26efec6b8d9d25946b42510ad377360176044ec
