### ISSUE TITLE
to & toEnd messages

### ISSUE THREAD

**Issue by stdavis** [steveoh/grunt-esri-slurp#36]
When loading this task in your project you get two messages:
```
to: wrong arguments
toEnd: wrong arguments
```
Verbose shows:
```
Registering "grunt-esri-slurp" local Npm module tasks.
Reading /Users/stdavis/Documents/Projects/ugs-chemistry/node_modules/grunt-esri-slurp/package.json...OK
Parsing /Users/stdavis/Documents/Projects/ugs-chemistry/node_modules/grunt-esri-slurp/package.json...OK
to: wrong arguments

toEnd: wrong arguments

Loading "index.js" tasks...OK
+ esri_slurp, esri_slurp_modules
```

Would be nice to clean this up. Not sure what's causing it.

**Comment by steveoh** [comment]
related issues...

https://github.com/jprichardson/string.js/pull/128
https://github.com/jprichardson/string.js/issues/127
https://github.com/arturadib/shelljs/issues/159

We'd have to remove the dependency on string.js. Shouldn't be too hard to cherry pick the methods I use.

**Comment by stdavis** [comment]
Thanks!
