### ISSUE TITLE
grunt-esri-slurp 2.0.2 - Doesn't download content of "dojox\dgauges"

### ISSUE THREAD

**Issue by Vikash2402** [steveoh/grunt-esri-slurp#40]
Hi,
While running grunt slurp it downloads "dojox\dgauges" folder empty. it creates empty dgauges folder under dojox.

Note: Arcgis JS API 3.14

Any suggestion why its happening?

thanks in advance.

**Comment by Vikash2402** [comment]
To resolve this I have a wok around I downloaded Arcgis JS API 3.14 package offline and replace the "dgauges" folder from it. and it started working.
But I dont think its correct.
Plz suggest.

**Comment by stdavis** [comment]
This project is intended to only download the `esri` package. Any other package including `dojox` or `dstore` should be downloaded (using something like bower) separately.

**Comment by steveoh** [comment]
And mapped for builds

https://github.com/steveoh/grunt-esri-slurp/issues/38
