### ISSUE TITLE
grunt-esri-slurp 2.0.2 - dstore not working properly

### ISSUE THREAD

**Issue by Vikash2402** [steveoh/grunt-esri-slurp#41]
Hi,

I am developing an esri-javascript map based web application with minification; while creating build using grunt it throws en error i.e.
**error(311) Missing dependency.
	module: app/js/library/widgets/searchGrid/searchGrid; dependency: dstore/Memory**
I verified the arcgis js api 3.14 package and I am able to find dstore in it. 
still its thorwing this error.

It would be great if you can throw some pointers on it.

Thanks in advance.

**Comment by stdavis** [comment]
https://github.com/steveoh/grunt-esri-slurp/issues/40#issuecomment-165786194

**Comment by steveoh** [comment]
Yes as @stdavis mentions, you will need to pull in these dependencies separately. We use bower. Here is an example [dependency list](https://github.com/agrc/AGRCJavaScriptProjectBoilerPlate/blob/master/bower.json).

In all seriousness, you should consider stopping using this module and use the [esri package](https://github.com/Esri/arcgis-js-api) which is published to bower.
